---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/**/*
- db/**/*
- features/**/*
- script/**/*
- spec/**/*
- vendor/**/*
engines:
  # ... CONFIG CONTENT ...
  brakeman:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - 32ff2c524d8067c94f76065cc2513a6f7c21219566051389941d6d00b370b356
    - eb0eda9ff60a50f076dc78f70958257820c1b49aeb06424bfde68112123ed74b
    - 9d34f74a63bc5c80fb5cdc8d06a619b967eb04eae3423b780d577076d40a26c2
# ... CONFIG CONTENT ...
