defaults: &defaults
  access_key_id: <%= Rails.application.secrets.amazon_access_key_id %>
  secret_access_key: <%= Rails.application.secrets.amazon_secret_access_key %>
  acl: public-read # options: private, public-read, public-read-write, authenticated-read
  max_file_size: 524288000 # 500 megabytes

development:
  <<: *defaults
  bucket: <%= Rails.application.secrets.amazon_bucket %>

test:
  <<: *defaults
  bucket: <%= Rails.application.secrets.amazon_bucket %>

production:
  <<: *defaults
  bucket: <%= Rails.application.secrets.amazon_bucket %>
